version: '3.4'
services:
  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db/
    networks:
      - mongodb-n
  mongo-express:
    image: mongo-express
    container_name: gui
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongodb-n
  servertema2:
    build: .
    image: "servertema2:1"
    container_name: server
    depends_on:
      - mongodb
      - mongo-express
    ports:
      - 6000:6000
    networks:
      - mongodb-n
    #network_mode: host
volumes:
  mongo-data:
    driver: local
networks:
  mongodb-n:
    driver: bridge